Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 66, in main
    fmriprep_wf = retval.get("workflow", None)
  File "<string>", line 2, in get
  File "/opt/conda/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/reportlets/masks.py", line 39, in <module>
    from . import base as nrb
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/reportlets/base.py", line 27, in <module>
    from ...viz.utils import cuts_from_bbox, compose_view
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/viz/__init__.py", line 3, in <module>
    from .plots import plot_carpet
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/viz/plots.py", line 29, in <module>
    import matplotlib.pyplot as plt
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/colorbar.py", line 21, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/contour.py", line 13, in <module>
    from matplotlib.backend_bases import MouseButton
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/textpath.py", line 8, in <module>
    from matplotlib import _text_helpers, dviread, font_manager
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/font_manager.py", line 1447, in <module>
    fontManager = _load_fontmanager()
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/font_manager.py", line 1442, in _load_fontmanager
    json_dump(fm, fm_path)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/font_manager.py", line 1003, in json_dump
    with cbook._lock_path(filename), open(filename, 'w') as fh:
  File "/opt/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 1774, in _lock_path
    raise TimeoutError("""\
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds002748-fmriprep/code/containers/binds/HOME/.cache/matplotlib/fontlist-v330.json.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
